CREATE DATABASE dbProjeto



--EXECUTAR NA BASE CRIADA
CREATE TABLE PESSOAS(
CODPESSOA INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(150),
TELEFONE VARCHAR(15),
PLACAVEICULO VARCHAR(8)
);

CREATE TABLE PESSOASERVICOPRESTADO (
CODSERVICO INT IDENTITY(1,1) PRIMARY KEY,
CODPESSOA INT FOREIGN KEY REFERENCES PESSOAS (CODPESSOA),
DESCRICAOSERVICO VARCHAR(MAX),
DATASERVICO DATETIME,
);

